wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.42.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721163001
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 23
      4: 3.9.19
      5: 0.17.4
      6: 4.42.4
      8:
      - 1
      - 5
      13: linux-x86_64
